# Generated by Django 2.2.3 on 2019-07-13 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('director', models.CharField(max_length=100, verbose_name='director')),
                ('writer', models.CharField(max_length=100, verbose_name='writer')),
                ('stars', models.PositiveSmallIntegerField(verbose_name='stars')),
                ('summary', models.TextField(verbose_name='summary')),
                ('year', models.CharField(default=2019, max_length=4, verbose_name='year')),
                ('category', models.CharField(choices=[('comedy', 'Comedy'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('romantic', 'Romantic'), ('sfx', 'Science Fiction')], max_length=100, verbose_name='category')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated At')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='deleted At')),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_by', to=settings.AUTH_USER_MODEL, verbose_name='registered by')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'ordering': ['stars'],
            },
        ),
    ]
